language: php
before_script: composer install && composer require paragonie/random_compat
script: ./vendor/bin/phpunit --bootstrap vendor/autoload.php test
php:
  - '5.6'
  - '7.1'
  - '7.2'
  - nightly